services:
    newscoop_ingest_plugin.lifecyclesubscriber:
        class: Newscoop\IngestPluginBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
            - @newscoop_ingest_plugin.articletypeconfigurator
            - @dispatcher
        tags:
            - { name: kernel.event_subscriber}

    newscoop_ingest_plugin.configure_menu_listener:
        class: Newscoop\IngestPluginBundle\EventListener\ConfigureMenuListener
        tags:
            - { name: kernel.event_listener, event: newscoop_newscoop.menu_configure, method: onMenuConfigure }
        arguments:
            - @translator

    newscoop_ingest_plugin.ingest_parsers.listener:
        class: Newscoop\IngestPluginBundle\EventListener\IngestParsersListener
        arguments: ["@em"]
        tags:
          - { name: kernel.event_listener, event: newscoop_ingest.parser.register, method: registerExternalParsers }

    newscoop_ingest_plugin.ingester:
        class:      Newscoop\IngestPluginBundle\Services\IngestService
        arguments:
            - "@em"
            - "@newscoop_ingest_plugin.publisher"
            - "@newscoop_ingest_plugin.articletypeconfigurator"
            - "@logger"

    newscoop_ingest_plugin.publisher:
        class:      Newscoop\IngestPluginBundle\Services\PublisherService
        arguments:
            - "@em"
            - "@newscoop_ingest_plugin.articletypeconfigurator"

    newscoop_ingest_plugin.articletypeconfigurator:
        class:      Newscoop\IngestPluginBundle\Services\ArticleTypeConfigurationService
        arguments:
            - "@em"
            - "@doctrine.adodb"

    newscoop_ingest_plugin.article_subscriber:
        class:      Newscoop\IngestPluginBundle\EventListener\ArticleSubscriber
        arguments:  ["@em"]
        tags:
            -  { name: kernel.event_listener, event: article.publish, method: publish }
            -  { name: kernel.event_listener, event: article.published, method: publish }
            -  { name: kernel.event_listener, event: article.delete, method: delete }

    newscoop_ingest_plugin.issue_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Newscoop\Entity\Issue

    newscoop_ingest_plugin.section_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Newscoop\Entity\Section

    newscoop_ingest_plugin.topic_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Newscoop\NewscoopBundle\Entity\Topic

    newscoop_ingest_plugin.issue_selecter:
        class:      Newscoop\IngestPluginBundle\Form\Type\EntitySelectorType
        arguments:
            - "issue_selecter"
            - @em
            - @newscoop_ingest_plugin.issue_repository
        tags:
          - { name: form.type, alias: "issue_selecter"}

    newscoop_ingest_plugin.section_selecter:
        class:      Newscoop\IngestPluginBundle\Form\Type\EntitySelectorType
        arguments:
            - "section_selecter"
            - @em
            - @newscoop_ingest_plugin.section_repository
        tags:
          - { name: form.type, alias: "section_selecter"}

    newscoop_ingest_plugin.topic_selecter:
        class:      Newscoop\IngestPluginBundle\Form\Type\EntitySelectorType
        arguments:
            - "topic_selecter"
            - @em
            - @newscoop_ingest_plugin.topic_repository
        tags:
          - { name: form.type, alias: "topic_selecter"}
